version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
    volumes:
      - .:/grabber
    ports:
      - "3000:3000"
    depends_on:
      - db
