source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'api-pagination'
gem 'awesome_pry'
gem 'dotenv'
gem 'dry-initializer', '~> 2.5.0'
gem 'faraday', '~> 0.10'
gem 'faraday_middleware'
gem 'faraday_middleware-parse_oj'
gem 'grape'
gem 'grape_on_rails_routes'
gem 'grape-entity'
gem 'kaminari'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.12'
gem 'rails', '~> 5.0.7'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
